### PR TITLE
Update TemplateModel.php

### PR DESCRIPTION
**Pull request by chrisastley**
Add findById function. This is useful instead of hard coding in the names of the templates in case you want to be able to edit the names without breaking functionality.

### CODE REVIEW

**Review by MGatner — COMMENTED** [review]
I'm not sure this is merited since it is just `find()`. Is the goal to have the exception? Why wouldn't you handle this yourself?

**Comment by chrisastley** [comment]
This is to allow the same/similar method to be used.

> model(TemplateModel::class)->findByName('Default')
	->email([
		'item' => 'Fancy Purse',
		'cost' => '10 dollars',
		'url'  => site_url('items/show/' . $itemId),
	])
	->setTo($user->email)
	->send();

So that would become

> model(TemplateModel::class)->findById(1)
	->email([
		'item' => 'Fancy Purse',
		'cost' => '10 dollars',
		'url'  => site_url('items/show/' . $itemId),
	])
	->setTo($user->email)
	->send();

Meaning that you could change template names without breaking the first option.

**Comment by MGatner** [comment]
I understand the use case, but I'm trying to point out that your method is the same as `Model::find()` with an added exception. In your example:
```
model(TemplateModel::class)->findById(1) // this line
model(TemplateModel::class)->find(1) // ...can be written like this
```

**Comment by chrisastley** [comment]
Ahh ok, apologies as I wasn't aware that could be done. I'm still learning CI4 and didn't have a great deal of knowledge of CI3 beforehand.

**Pull request closed without merging**
